set dotenv-required := true

# Define MOD_PATH in .env
# RainWorld_Data/StreamingAssets/mods/
# No backslashes in path

[default]
build:
    if [ -f plugin/*.csproj ]; then \
        dotnet publish -c Release -p:SkipCopyMod=true plugin/*.csproj; \
    fi

[arg("mods_dir", help="Default is MOD_PATH env var if empty")]
[script]
install mods_dir='': build
    mods_dir='{{ mods_dir }}'
    if [ '{{ trim(mods_dir) }}' = '' ]; then
        {{ assert(trim(env('MOD_PATH', '')) != '', 'Missing or empty MOD_PATH env var') }}
        mods_dir="$MOD_PATH"
    fi

    dest="$mods_dir/{{ file_name(justfile_directory()) }}"

    echo "Copying mod to \"$dest\""

    rm -rf "$dest"
    mkdir -p "$dest"

    find . -mindepth 1 -maxdepth 1 ! -name 'plugin' ! -name 'justfile' -exec cp -r {} "$dest" \;

    if [ -f plugin/*.csproj ]; then
        mkdir -p "$dest/plugins"
        cp -t "$dest/plugins" plugin/bin/Release/*/publish/*
    fi

# TODO: Add export recipe for zip archive
